---
title: "Trait aggregate correlations"
output: 
  html_document: 
    toc: yes
    number_sections: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparations

## Packages

```{r message=FALSE, warning=FALSE}
library(rio)
library(psych)
library(meta)
```

## Read data

```{r}
Danish<-import("../../data/processed/Danish/Dan_fdat.xlsx")
British<-import("../../data/processed/British/Brit_fdat.xlsx")
Chinese1<-import("../../data/processed/Chinese 1/Chi1_fdat.xlsx")
Chinese2<-import("../../data/processed/Chinese 2/Chi2_fdat.xlsx")
Chinese3<-import("../../data/processed/Chinese 3/Chi3comb_fdat.xlsx")
```

## Variables names

```{r}

OP.sr.vars<-
  paste0("hex",
         ifelse(c(seq(from=01, to =60,by=6))<10,
                paste0("0",c(seq(from=01, to =60,by=6))),
                c(seq(from=01, to =60,by=6))))

OP.sr.vars
OP.sr.revs<-c(1,4,6,9,10)

OP.pr.vars1<-paste0("cp",OP.sr.vars)
OP.pr.vars2<-paste0("p",OP.sr.vars)

CO.sr.vars<-
  paste0("hex",
         ifelse(c(seq(from=02, to =60,by=6))<10,
                paste0("0",c(seq(from=02, to =60,by=6))),
                c(seq(from=02, to =60,by=6))))

CO.sr.vars
CO.sr.revs<-c(3,4,5,6,8,10)

CO.pr.vars1<-paste0("cp",CO.sr.vars)
CO.pr.vars2<-paste0("p",CO.sr.vars)

AG.sr.vars<-
  paste0("hex",
         ifelse(c(seq(from=03, to =60,by=6))<10,
                paste0("0",c(seq(from=03, to =60,by=6))),
                c(seq(from=03, to =60,by=6))))

AG.sr.vars
AG.sr.revs<-c(2,3,4,10)

AG.pr.vars1<-paste0("cp",AG.sr.vars)
AG.pr.vars2<-paste0("p",AG.sr.vars)

EX.sr.vars<-
  paste0("hex",
         ifelse(c(seq(from=04, to =60,by=6))<10,
                paste0("0",c(seq(from=04, to =60,by=6))),
                c(seq(from=04, to =60,by=6))))

EX.sr.vars
EX.sr.revs<-c(2,5,8,9)

EX.pr.vars1<-paste0("cp",EX.sr.vars)
EX.pr.vars2<-paste0("p",EX.sr.vars)

EM.sr.vars<-
  paste0("hex",
         ifelse(c(seq(from=05, to =60,by=6))<10,
                paste0("0",c(seq(from=05, to =60,by=6))),
                c(seq(from=05, to =60,by=6))))

EM.sr.vars
EM.sr.revs<-c(6,7,9,10)

EM.pr.vars1<-paste0("cp",EM.sr.vars)
EM.pr.vars2<-paste0("p",EM.sr.vars)

HH.sr.vars<-
  paste0("hex",
         ifelse(c(seq(from=06, to =60,by=6))<10,
                paste0("0",c(seq(from=06, to =60,by=6))),
                c(seq(from=06, to =60,by=6))))

HH.sr.vars
HH.sr.revs<-c(2,4,5,7,8,10)

HH.pr.vars1<-paste0("cp",HH.sr.vars)
HH.pr.vars2<-paste0("p",HH.sr.vars)


```

## Calculate scale means

### Danish

```{r}
#AG

#reverse coded self-ratings
Danish[,AG.sr.vars[AG.sr.revs]]<-
  6-Danish[,AG.sr.vars[AG.sr.revs]]

#reverse coded couple-ratings
Danish[,AG.pr.vars1[AG.sr.revs]]<-
  6-Danish[,AG.pr.vars1[AG.sr.revs]]

#CO

#reverse coded self-ratings
Danish[,CO.sr.vars[CO.sr.revs]]<-
  6-Danish[,CO.sr.vars[CO.sr.revs]]

#reverse coded couple-ratings
Danish[,CO.pr.vars1[CO.sr.revs]]<-
  6-Danish[,CO.pr.vars1[CO.sr.revs]]

#EM

#reverse coded self-ratings
Danish[,EM.sr.vars[EM.sr.revs]]<-
  6-Danish[,EM.sr.vars[EM.sr.revs]]

#reverse coded couple-ratings
Danish[,EM.pr.vars1[EM.sr.revs]]<-
  6-Danish[,EM.pr.vars1[EM.sr.revs]]

#EX

#reverse coded self-ratings
Danish[,EX.sr.vars[EX.sr.revs]]<-
  6-Danish[,EX.sr.vars[EX.sr.revs]]

#reverse coded couple-ratings
Danish[,EX.pr.vars1[EX.sr.revs]]<-
  6-Danish[,EX.pr.vars1[EX.sr.revs]]

#HH

#reverse coded self-ratings
Danish[,HH.sr.vars[HH.sr.revs]]<-
  6-Danish[,HH.sr.vars[HH.sr.revs]]

#reverse coded couple-ratings
Danish[,HH.pr.vars1[HH.sr.revs]]<-
  6-Danish[,HH.pr.vars1[HH.sr.revs]]

#OP

#reverse coded self-ratings
Danish[,OP.sr.vars[OP.sr.revs]]<-
  6-Danish[,OP.sr.vars[OP.sr.revs]]

#reverse coded couple-ratings
Danish[,OP.pr.vars1[OP.sr.revs]]<-
  6-Danish[,OP.pr.vars1[OP.sr.revs]]

#calculate scale means
Danish$sr.AG<-rowMeans(Danish[,AG.sr.vars])
Danish$sr.CO<-rowMeans(Danish[,CO.sr.vars])
Danish$sr.EM<-rowMeans(Danish[,EM.sr.vars])
Danish$sr.EX<-rowMeans(Danish[,EX.sr.vars])
Danish$sr.HH<-rowMeans(Danish[,HH.sr.vars])
Danish$sr.OP<-rowMeans(Danish[,OP.sr.vars])

Danish$pr.AG<-rowMeans(Danish[,AG.pr.vars1])
Danish$pr.CO<-rowMeans(Danish[,CO.pr.vars1])
Danish$pr.EM<-rowMeans(Danish[,EM.pr.vars1])
Danish$pr.EX<-rowMeans(Danish[,EX.pr.vars1])
Danish$pr.HH<-rowMeans(Danish[,HH.pr.vars1])
Danish$pr.OP<-rowMeans(Danish[,OP.pr.vars1])

```


### British

```{r}
#AG

#reverse coded self-ratings
British[,AG.sr.vars[AG.sr.revs]]<-
  6-British[,AG.sr.vars[AG.sr.revs]]

#reverse coded couple-ratings
British[,AG.pr.vars2[AG.sr.revs]]<-
  6-British[,AG.pr.vars2[AG.sr.revs]]

#CO

#reverse coded self-ratings
British[,CO.sr.vars[CO.sr.revs]]<-
  6-British[,CO.sr.vars[CO.sr.revs]]

#reverse coded couple-ratings
British[,CO.pr.vars2[CO.sr.revs]]<-
  6-British[,CO.pr.vars2[CO.sr.revs]]

#EM

#reverse coded self-ratings
British[,EM.sr.vars[EM.sr.revs]]<-
  6-British[,EM.sr.vars[EM.sr.revs]]

#reverse coded couple-ratings
British[,EM.pr.vars2[EM.sr.revs]]<-
  6-British[,EM.pr.vars2[EM.sr.revs]]

#EX

#reverse coded self-ratings
British[,EX.sr.vars[EX.sr.revs]]<-
  6-British[,EX.sr.vars[EX.sr.revs]]

#reverse coded couple-ratings
British[,EX.pr.vars2[EX.sr.revs]]<-
  6-British[,EX.pr.vars2[EX.sr.revs]]

#HH

#reverse coded self-ratings
British[,HH.sr.vars[HH.sr.revs]]<-
  6-British[,HH.sr.vars[HH.sr.revs]]

#reverse coded couple-ratings
British[,HH.pr.vars2[HH.sr.revs]]<-
  6-British[,HH.pr.vars2[HH.sr.revs]]

#OP

#reverse coded self-ratings
British[,OP.sr.vars[OP.sr.revs]]<-
  6-British[,OP.sr.vars[OP.sr.revs]]

#reverse coded couple-ratings
British[,OP.pr.vars2[OP.sr.revs]]<-
  6-British[,OP.pr.vars2[OP.sr.revs]]

#calculate scale means
British$sr.AG<-rowMeans(British[,AG.sr.vars])
British$sr.CO<-rowMeans(British[,CO.sr.vars])
British$sr.EM<-rowMeans(British[,EM.sr.vars])
British$sr.EX<-rowMeans(British[,EX.sr.vars])
British$sr.HH<-rowMeans(British[,HH.sr.vars])
British$sr.OP<-rowMeans(British[,OP.sr.vars])

British$pr.AG<-rowMeans(British[,AG.pr.vars2])
British$pr.CO<-rowMeans(British[,CO.pr.vars2])
British$pr.EM<-rowMeans(British[,EM.pr.vars2])
British$pr.EX<-rowMeans(British[,EX.pr.vars2])
British$pr.HH<-rowMeans(British[,HH.pr.vars2])
British$pr.OP<-rowMeans(British[,OP.pr.vars2])

```

### Chinese1

```{r}
#AG

#reverse coded self-ratings
Chinese1[,AG.sr.vars[AG.sr.revs]]<-
  6-Chinese1[,AG.sr.vars[AG.sr.revs]]

#reverse coded couple-ratings
Chinese1[,AG.pr.vars2[AG.sr.revs]]<-
  6-Chinese1[,AG.pr.vars2[AG.sr.revs]]

#CO

#reverse coded self-ratings
Chinese1[,CO.sr.vars[CO.sr.revs]]<-
  6-Chinese1[,CO.sr.vars[CO.sr.revs]]

#reverse coded couple-ratings
Chinese1[,CO.pr.vars2[CO.sr.revs]]<-
  6-Chinese1[,CO.pr.vars2[CO.sr.revs]]

#EM

#reverse coded self-ratings
Chinese1[,EM.sr.vars[EM.sr.revs]]<-
  6-Chinese1[,EM.sr.vars[EM.sr.revs]]

#reverse coded couple-ratings
Chinese1[,EM.pr.vars2[EM.sr.revs]]<-
  6-Chinese1[,EM.pr.vars2[EM.sr.revs]]

#EX

#reverse coded self-ratings
Chinese1[,EX.sr.vars[EX.sr.revs]]<-
  6-Chinese1[,EX.sr.vars[EX.sr.revs]]

#reverse coded couple-ratings
Chinese1[,EX.pr.vars2[EX.sr.revs]]<-
  6-Chinese1[,EX.pr.vars2[EX.sr.revs]]

#HH

#reverse coded self-ratings
Chinese1[,HH.sr.vars[HH.sr.revs]]<-
  6-Chinese1[,HH.sr.vars[HH.sr.revs]]

#reverse coded couple-ratings
Chinese1[,HH.pr.vars2[HH.sr.revs]]<-
  6-Chinese1[,HH.pr.vars2[HH.sr.revs]]

#OP

#reverse coded self-ratings
Chinese1[,OP.sr.vars[OP.sr.revs]]<-
  6-Chinese1[,OP.sr.vars[OP.sr.revs]]

#reverse coded couple-ratings
Chinese1[,OP.pr.vars2[OP.sr.revs]]<-
  6-Chinese1[,OP.pr.vars2[OP.sr.revs]]

#calculate scale means
Chinese1$sr.AG<-rowMeans(Chinese1[,AG.sr.vars])
Chinese1$sr.CO<-rowMeans(Chinese1[,CO.sr.vars])
Chinese1$sr.EM<-rowMeans(Chinese1[,EM.sr.vars])
Chinese1$sr.EX<-rowMeans(Chinese1[,EX.sr.vars])
Chinese1$sr.HH<-rowMeans(Chinese1[,HH.sr.vars])
Chinese1$sr.OP<-rowMeans(Chinese1[,OP.sr.vars])

Chinese1$pr.AG<-rowMeans(Chinese1[,AG.pr.vars2])
Chinese1$pr.CO<-rowMeans(Chinese1[,CO.pr.vars2])
Chinese1$pr.EM<-rowMeans(Chinese1[,EM.pr.vars2])
Chinese1$pr.EX<-rowMeans(Chinese1[,EX.pr.vars2])
Chinese1$pr.HH<-rowMeans(Chinese1[,HH.pr.vars2])
Chinese1$pr.OP<-rowMeans(Chinese1[,OP.pr.vars2])

```

### Chinese2

```{r}
#AG

#reverse coded self-ratings
Chinese2[,AG.sr.vars[AG.sr.revs]]<-
  6-Chinese2[,AG.sr.vars[AG.sr.revs]]

#reverse coded couple-ratings
Chinese2[,AG.pr.vars2[AG.sr.revs]]<-
  6-Chinese2[,AG.pr.vars2[AG.sr.revs]]

#CO

#reverse coded self-ratings
Chinese2[,CO.sr.vars[CO.sr.revs]]<-
  6-Chinese2[,CO.sr.vars[CO.sr.revs]]

#reverse coded couple-ratings
Chinese2[,CO.pr.vars2[CO.sr.revs]]<-
  6-Chinese2[,CO.pr.vars2[CO.sr.revs]]

#EM

#reverse coded self-ratings
Chinese2[,EM.sr.vars[EM.sr.revs]]<-
  6-Chinese2[,EM.sr.vars[EM.sr.revs]]

#reverse coded couple-ratings
Chinese2[,EM.pr.vars2[EM.sr.revs]]<-
  6-Chinese2[,EM.pr.vars2[EM.sr.revs]]

#EX

#reverse coded self-ratings
Chinese2[,EX.sr.vars[EX.sr.revs]]<-
  6-Chinese2[,EX.sr.vars[EX.sr.revs]]

#reverse coded couple-ratings
Chinese2[,EX.pr.vars2[EX.sr.revs]]<-
  6-Chinese2[,EX.pr.vars2[EX.sr.revs]]

#HH

#reverse coded self-ratings
Chinese2[,HH.sr.vars[HH.sr.revs]]<-
  6-Chinese2[,HH.sr.vars[HH.sr.revs]]

#reverse coded couple-ratings
Chinese2[,HH.pr.vars2[HH.sr.revs]]<-
  6-Chinese2[,HH.pr.vars2[HH.sr.revs]]

#OP

#reverse coded self-ratings
Chinese2[,OP.sr.vars[OP.sr.revs]]<-
  6-Chinese2[,OP.sr.vars[OP.sr.revs]]

#reverse coded couple-ratings
Chinese2[,OP.pr.vars2[OP.sr.revs]]<-
  6-Chinese2[,OP.pr.vars2[OP.sr.revs]]

#calculate scale means
Chinese2$sr.AG<-rowMeans(Chinese2[,AG.sr.vars])
Chinese2$sr.CO<-rowMeans(Chinese2[,CO.sr.vars])
Chinese2$sr.EM<-rowMeans(Chinese2[,EM.sr.vars])
Chinese2$sr.EX<-rowMeans(Chinese2[,EX.sr.vars])
Chinese2$sr.HH<-rowMeans(Chinese2[,HH.sr.vars])
Chinese2$sr.OP<-rowMeans(Chinese2[,OP.sr.vars])

Chinese2$pr.AG<-rowMeans(Chinese2[,AG.pr.vars2])
Chinese2$pr.CO<-rowMeans(Chinese2[,CO.pr.vars2])
Chinese2$pr.EM<-rowMeans(Chinese2[,EM.pr.vars2])
Chinese2$pr.EX<-rowMeans(Chinese2[,EX.pr.vars2])
Chinese2$pr.HH<-rowMeans(Chinese2[,HH.pr.vars2])
Chinese2$pr.OP<-rowMeans(Chinese2[,OP.pr.vars2])

```

### Chinese3

```{r}
#AG

#reverse coded self-ratings
Chinese3[,AG.sr.vars[AG.sr.revs]]<-
  6-Chinese3[,AG.sr.vars[AG.sr.revs]]

#reverse coded couple-ratings
Chinese3[,AG.pr.vars2[AG.sr.revs]]<-
  6-Chinese3[,AG.pr.vars2[AG.sr.revs]]

#CO

#reverse coded self-ratings
Chinese3[,CO.sr.vars[CO.sr.revs]]<-
  6-Chinese3[,CO.sr.vars[CO.sr.revs]]

#reverse coded couple-ratings
Chinese3[,CO.pr.vars2[CO.sr.revs]]<-
  6-Chinese3[,CO.pr.vars2[CO.sr.revs]]

#EM

#reverse coded self-ratings
Chinese3[,EM.sr.vars[EM.sr.revs]]<-
  6-Chinese3[,EM.sr.vars[EM.sr.revs]]

#reverse coded couple-ratings
Chinese3[,EM.pr.vars2[EM.sr.revs]]<-
  6-Chinese3[,EM.pr.vars2[EM.sr.revs]]

#EX

#reverse coded self-ratings
Chinese3[,EX.sr.vars[EX.sr.revs]]<-
  6-Chinese3[,EX.sr.vars[EX.sr.revs]]

#reverse coded couple-ratings
Chinese3[,EX.pr.vars2[EX.sr.revs]]<-
  6-Chinese3[,EX.pr.vars2[EX.sr.revs]]

#HH

#reverse coded self-ratings
Chinese3[,HH.sr.vars[HH.sr.revs]]<-
  6-Chinese3[,HH.sr.vars[HH.sr.revs]]

#reverse coded couple-ratings
Chinese3[,HH.pr.vars2[HH.sr.revs]]<-
  6-Chinese3[,HH.pr.vars2[HH.sr.revs]]

#OP

#reverse coded self-ratings
Chinese3[,OP.sr.vars[OP.sr.revs]]<-
  6-Chinese3[,OP.sr.vars[OP.sr.revs]]

#reverse coded couple-ratings
Chinese3[,OP.pr.vars2[OP.sr.revs]]<-
  6-Chinese3[,OP.pr.vars2[OP.sr.revs]]

#calculate scale means
Chinese3$sr.AG<-rowMeans(Chinese3[,AG.sr.vars])
Chinese3$sr.CO<-rowMeans(Chinese3[,CO.sr.vars])
Chinese3$sr.EM<-rowMeans(Chinese3[,EM.sr.vars])
Chinese3$sr.EX<-rowMeans(Chinese3[,EX.sr.vars])
Chinese3$sr.HH<-rowMeans(Chinese3[,HH.sr.vars])
Chinese3$sr.OP<-rowMeans(Chinese3[,OP.sr.vars])

Chinese3$pr.AG<-rowMeans(Chinese3[,AG.pr.vars2])
Chinese3$pr.CO<-rowMeans(Chinese3[,CO.pr.vars2])
Chinese3$pr.EM<-rowMeans(Chinese3[,EM.pr.vars2])
Chinese3$pr.EX<-rowMeans(Chinese3[,EX.pr.vars2])
Chinese3$pr.HH<-rowMeans(Chinese3[,HH.pr.vars2])
Chinese3$pr.OP<-rowMeans(Chinese3[,OP.pr.vars2])

```

## Scale names

```{r}
sr.scales<-c("sr.AG",
             "sr.CO",
             "sr.EM",
             "sr.EX",
             "sr.HH",
             "sr.OP")

pr.scales<-c("pr.AG",
             "pr.CO",
             "pr.EM",
             "pr.EX",
             "pr.HH",
             "pr.OP")
```


# Calculate correlations


## Danish

```{r}


Danish.cors<-corr.test(Danish[,c(sr.scales,pr.scales)],
                adjust="none")

Danish.cors.list<-list()


for (i in 1:length(sr.scales)){
  corr<-Danish.cors$r[sr.scales[i],pr.scales[i]]
  se<-Danish.cors$se[sr.scales[i],pr.scales[i]]
  t.val<-Danish.cors$t[sr.scales[i],pr.scales[i]]
  p<-Danish.cors$p[sr.scales[i],pr.scales[i]]
  
  Danish.cors.list[[i]]<-cbind.data.frame(
    trait=sr.scales[i],r=corr,se=se,t=t.val,p=p
  )
  
}

Danish.cors.df<-do.call(rbind.data.frame,Danish.cors.list)
cbind.data.frame(trait=substr(Danish.cors.df$trait,4,5),
                 round(Danish.cors.df[,2:4],2),
                 p=round(Danish.cors.df[,5],3))

export(Danish.cors.df,"../../output/Danish/trait.agg.cors.xlsx")
```

## British

```{r}


British.cors<-corr.test(British[,c(sr.scales,pr.scales)],
                adjust="none")

British.cors.list<-list()


for (i in 1:length(sr.scales)){
  corr<-British.cors$r[sr.scales[i],pr.scales[i]]
  se<-British.cors$se[sr.scales[i],pr.scales[i]]
  t.val<-British.cors$t[sr.scales[i],pr.scales[i]]
  p<-British.cors$p[sr.scales[i],pr.scales[i]]
  
  British.cors.list[[i]]<-cbind.data.frame(
    trait=sr.scales[i],r=corr,se=se,t=t.val,p=p
  )
  
}

British.cors.df<-do.call(rbind.data.frame,British.cors.list)
cbind.data.frame(trait=substr(British.cors.df$trait,4,5),
                 round(British.cors.df[,2:4],2),
                 p=round(British.cors.df[,5],3))

export(British.cors.df,"../../output/British/trait.agg.cors.xlsx")
```


## Chinese1

```{r}


Chinese1.cors<-corr.test(Chinese1[,c(sr.scales,pr.scales)],
                adjust="none")

Chinese1.cors.list<-list()


for (i in 1:length(sr.scales)){
  corr<-Chinese1.cors$r[sr.scales[i],pr.scales[i]]
  se<-Chinese1.cors$se[sr.scales[i],pr.scales[i]]
  t.val<-Chinese1.cors$t[sr.scales[i],pr.scales[i]]
  p<-Chinese1.cors$p[sr.scales[i],pr.scales[i]]
  
  Chinese1.cors.list[[i]]<-cbind.data.frame(
    trait=sr.scales[i],r=corr,se=se,t=t.val,p=p
  )
  
}

Chinese1.cors.df<-do.call(rbind.data.frame,Chinese1.cors.list)
cbind.data.frame(trait=substr(Chinese1.cors.df$trait,4,5),
                 round(Chinese1.cors.df[,2:4],2),
                 p=round(Chinese1.cors.df[,5],3))

export(Chinese1.cors.df,"../../output/Chinese 1/trait.agg.cors.xlsx")
```

## Chinese2

```{r}


Chinese2.cors<-corr.test(Chinese2[,c(sr.scales,pr.scales)],
                adjust="none")

Chinese2.cors.list<-list()


for (i in 1:length(sr.scales)){
  corr<-Chinese2.cors$r[sr.scales[i],pr.scales[i]]
  se<-Chinese2.cors$se[sr.scales[i],pr.scales[i]]
  t.val<-Chinese2.cors$t[sr.scales[i],pr.scales[i]]
  p<-Chinese2.cors$p[sr.scales[i],pr.scales[i]]
  
  Chinese2.cors.list[[i]]<-cbind.data.frame(
    trait=sr.scales[i],r=corr,se=se,t=t.val,p=p
  )
  
}

Chinese2.cors.df<-do.call(rbind.data.frame,Chinese2.cors.list)
cbind.data.frame(trait=substr(Chinese2.cors.df$trait,4,5),
                 round(Chinese2.cors.df[,2:4],2),
                 p=round(Chinese2.cors.df[,5],3))

export(Chinese2.cors.df,"../../output/Chinese 2/trait.agg.cors.xlsx")
```

## Chinese3

```{r}


Chinese3.cors<-corr.test(Chinese3[,c(sr.scales,pr.scales)],
                adjust="none")

Chinese3.cors.list<-list()


for (i in 1:length(sr.scales)){
  corr<-Chinese3.cors$r[sr.scales[i],pr.scales[i]]
  se<-Chinese3.cors$se[sr.scales[i],pr.scales[i]]
  t.val<-Chinese3.cors$t[sr.scales[i],pr.scales[i]]
  p<-Chinese3.cors$p[sr.scales[i],pr.scales[i]]
  
  Chinese3.cors.list[[i]]<-cbind.data.frame(
    trait=sr.scales[i],r=corr,se=se,t=t.val,p=p
  )
  
}

Chinese3.cors.df<-do.call(rbind.data.frame,Chinese3.cors.list)
cbind.data.frame(trait=substr(Chinese3.cors.df$trait,4,5),
                 round(Chinese3.cors.df[,2:4],2),
                 p=round(Chinese3.cors.df[,5],3))

export(Chinese3.cors.df,"../../output/Chinese 3/trait.agg.cors.xlsx")
```

## Meta-analytical

### AG

```{r}

AG.eff<-data.frame(
  r=
  c(
    Danish.cors.df[Danish.cors.df$trait=="sr.AG","r"],
    British.cors.df[British.cors.df$trait=="sr.AG","r"],
    Chinese1.cors.df[Chinese1.cors.df$trait=="sr.AG","r"],
    Chinese2.cors.df[Chinese2.cors.df$trait=="sr.AG","r"],
    Chinese3.cors.df[Chinese3.cors.df$trait=="sr.AG","r"]),
  n=
    c(nrow(Danish),
      nrow(British),
      nrow(Chinese1),
      nrow(Chinese2),
      nrow(Chinese3)))
  
m.AG<-metacor(cor = AG.eff$r,n=AG.eff$n,
              sm="ZCOR",comb.fixed=F,
              method.tau="ML",
              studlab=c("Danish",
                        "British Isles",
                        "Chinese 1",
                        "Chinese 2",
                        "Chinese 3"))

m.AG

m.AG.row<-
  cbind.data.frame(
  trait="AG",
  eff=m.AG$TE.random,
  se=m.AG$seTE.random,
  z=m.AG$zval.random,
  p=m.AG$pval.random
)
```


### CO

```{r}

CO.eff<-data.frame(
  r=
  c(
    Danish.cors.df[Danish.cors.df$trait=="sr.CO","r"],
    British.cors.df[British.cors.df$trait=="sr.CO","r"],
    Chinese1.cors.df[Chinese1.cors.df$trait=="sr.CO","r"],
    Chinese2.cors.df[Chinese2.cors.df$trait=="sr.CO","r"],
    Chinese3.cors.df[Chinese3.cors.df$trait=="sr.CO","r"]),
  n=
    c(nrow(Danish),
      nrow(British),
      nrow(Chinese1),
      nrow(Chinese2),
      nrow(Chinese3)))
  
m.CO<-metacor(cor = CO.eff$r,n=CO.eff$n,
              sm="ZCOR",comb.fixed=F,
              method.tau="ML",
              studlab=c("Danish",
                        "British Isles",
                        "Chinese 1",
                        "Chinese 2",
                        "Chinese 3"))

m.CO

m.CO.row<-
  cbind.data.frame(
  trait="CO",
  eff=m.CO$TE.random,
  se=m.CO$seTE.random,
  z=m.CO$zval.random,
  p=m.CO$pval.random
)
```


### EM

```{r}

EM.eff<-data.frame(
  r=
  c(
    Danish.cors.df[Danish.cors.df$trait=="sr.EM","r"],
    British.cors.df[British.cors.df$trait=="sr.EM","r"],
    Chinese1.cors.df[Chinese1.cors.df$trait=="sr.EM","r"],
    Chinese2.cors.df[Chinese2.cors.df$trait=="sr.EM","r"],
    Chinese3.cors.df[Chinese3.cors.df$trait=="sr.EM","r"]),
  n=
    c(nrow(Danish),
      nrow(British),
      nrow(Chinese1),
      nrow(Chinese2),
      nrow(Chinese3)))
  
m.EM<-metacor(cor = EM.eff$r,n=EM.eff$n,
              sm="ZCOR",comb.fixed=F,
              method.tau="ML",
              studlab=c("Danish",
                        "British Isles",
                        "Chinese 1",
                        "Chinese 2",
                        "Chinese 3"))

m.EM

m.EM.row<-
  cbind.data.frame(
  trait="EM",
  eff=m.EM$TE.random,
  se=m.EM$seTE.random,
  z=m.EM$zval.random,
  p=m.EM$pval.random
)
```


### EX

```{r}

EX.eff<-data.frame(
  r=
  c(
    Danish.cors.df[Danish.cors.df$trait=="sr.EX","r"],
    British.cors.df[British.cors.df$trait=="sr.EX","r"],
    Chinese1.cors.df[Chinese1.cors.df$trait=="sr.EX","r"],
    Chinese2.cors.df[Chinese2.cors.df$trait=="sr.EX","r"],
    Chinese3.cors.df[Chinese3.cors.df$trait=="sr.EX","r"]),
  n=
    c(nrow(Danish),
      nrow(British),
      nrow(Chinese1),
      nrow(Chinese2),
      nrow(Chinese3)))
  
m.EX<-metacor(cor = EX.eff$r,n=EX.eff$n,
              sm="ZCOR",comb.fixed=F,
              method.tau="ML",
              studlab=c("Danish",
                        "British Isles",
                        "Chinese 1",
                        "Chinese 2",
                        "Chinese 3"))

m.EX

m.EX.row<-
  cbind.data.frame(
  trait="EX",
  eff=m.EX$TE.random,
  se=m.EX$seTE.random,
  z=m.EX$zval.random,
  p=m.EX$pval.random
)
```


### HH

```{r}

HH.eff<-data.frame(
  r=
  c(
    Danish.cors.df[Danish.cors.df$trait=="sr.HH","r"],
    British.cors.df[British.cors.df$trait=="sr.HH","r"],
    Chinese1.cors.df[Chinese1.cors.df$trait=="sr.HH","r"],
    Chinese2.cors.df[Chinese2.cors.df$trait=="sr.HH","r"],
    Chinese3.cors.df[Chinese3.cors.df$trait=="sr.HH","r"]),
  n=
    c(nrow(Danish),
      nrow(British),
      nrow(Chinese1),
      nrow(Chinese2),
      nrow(Chinese3)))
  
m.HH<-metacor(cor = HH.eff$r,n=HH.eff$n,
              sm="ZCOR",comb.fixed=F,
              method.tau="ML",
              studlab=c("Danish",
                        "British Isles",
                        "Chinese 1",
                        "Chinese 2",
                        "Chinese 3"))

m.HH

m.HH.row<-
  cbind.data.frame(
  trait="HH",
  eff=m.HH$TE.random,
  se=m.HH$seTE.random,
  z=m.HH$zval.random,
  p=m.HH$pval.random
)
```


### OP

```{r}

OP.eff<-data.frame(
  r=
  c(
    Danish.cors.df[Danish.cors.df$trait=="sr.OP","r"],
    British.cors.df[British.cors.df$trait=="sr.OP","r"],
    Chinese1.cors.df[Chinese1.cors.df$trait=="sr.OP","r"],
    Chinese2.cors.df[Chinese2.cors.df$trait=="sr.OP","r"],
    Chinese3.cors.df[Chinese3.cors.df$trait=="sr.OP","r"]),
  n=
    c(nrow(Danish),
      nrow(British),
      nrow(Chinese1),
      nrow(Chinese2),
      nrow(Chinese3)))
  
m.OP<-metacor(cor = OP.eff$r,n=OP.eff$n,
              sm="ZCOR",comb.fixed=F,
              method.tau="ML",
              studlab=c("Danish",
                        "British Isles",
                        "Chinese 1",
                        "Chinese 2",
                        "Chinese 3"))

m.OP

m.OP.row<-
  cbind.data.frame(
  trait="OP",
  eff=m.OP$TE.random,
  se=m.OP$seTE.random,
  z=m.OP$zval.random,
  p=m.OP$pval.random
)
```

## Results to same table

```{r}
m.ALL<-
  rbind(m.AG.row,
        m.CO.row,
        m.EM.row,
        m.EX.row,
        m.HH.row,
        m.OP.row)

m.ALL

export(m.ALL,
       "../../output/Meta-analysis/Trait_aggregate_assumed_similarity.xlsx")
```

# Session information

```{r}
s<-sessionInfo()
print(s,locale=F)
```
